import { useState, useEffect } from 'react';
import { invoke } from "@tauri-apps/api/core";
import { CheckCircle2, ChevronDown, ChevronRight, X, FileText, GitBranch } from 'lucide-react';
import { RetroSpinner } from './ui/RetroSpinner';
import { cn } from '@/lib/utils';

/**
 * Small popover dialog showing completed tasks generated by LLM
 * Positioned at top-right of the terminal area
 * 
 * @param {boolean} open - Whether the dialog is visible
 * @param {function} onOpenChange - Callback when open state changes
 * @param {string} repoPath - Path to the git repository
 * @param {object} branchTasks - Hook state from useBranchTasks
 * @param {string} currentBranch - Current branch name
 */
export function BranchCompletedTasksDialog({ open, onOpenChange, repoPath, branchTasks, currentBranch }) {
  const [expandedTasks, setExpandedTasks] = useState(new Set());
  const [baseBranch, setBaseBranch] = useState(null);

  // Detect base branch when dialog opens
  useEffect(() => {
    if (open && repoPath) {
      // Try to detect base branch (main or master)
      const detectBaseBranch = async () => {
        try {
          // Check if main exists
          const result = await invoke('run_git_command', {
            repoPath,
            args: ['rev-parse', '--verify', 'main']
          });
          if (result && !result.includes('fatal')) {
            setBaseBranch('main');
            return;
          }
        } catch {}
        
        try {
          // Check if master exists
          const result = await invoke('run_git_command', {
            repoPath,
            args: ['rev-parse', '--verify', 'master']
          });
          if (result && !result.includes('fatal')) {
            setBaseBranch('master');
            return;
          }
        } catch {}
        
        // Default to main if we can't detect
        setBaseBranch('main');
      };
      
      detectBaseBranch();
    }
  }, [open, repoPath]);

  // Generate tasks when we have base branch and dialog is open
  useEffect(() => {
    if (open && repoPath && baseBranch && currentBranch && currentBranch !== baseBranch) {
      branchTasks.generateTasks(repoPath, baseBranch, currentBranch);
    }
  }, [open, repoPath, baseBranch, currentBranch]);

  // Track dialog open state for commit listener
  useEffect(() => {
    branchTasks.setDialogOpen(open);
  }, [open, branchTasks]);

  // Reset when dialog closes
  useEffect(() => {
    if (!open) {
      branchTasks.reset();
      setExpandedTasks(new Set());
      setBaseBranch(null);
    }
  }, [open]);

  const toggleTaskExpansion = (taskId) => {
    setExpandedTasks(prev => {
      const next = new Set(prev);
      if (next.has(taskId)) {
        next.delete(taskId);
      } else {
        next.add(taskId);
      }
      return next;
    });
  };

  const { stage, tasks, error } = branchTasks;

  if (!open) return null;

  return (
    <div 
      className="absolute top-2 right-2 z-50 w-80 max-h-[70vh] flex flex-col border border-dashed border-primary shadow bg-background"
    >
      {/* Header */}
      <div className="flex items-center justify-between p-2 border-b border-dashed border-border flex-shrink-0">
        <div className="flex items-center gap-2 min-w-0">
          <div className="flex flex-col min-w-0">
            <span className="font-mono text-sm font-medium truncate">Completed Tasks</span>
            {currentBranch && baseBranch && (
              <span className="font-mono text-xs text-muted-foreground truncate flex items-center gap-1">
                <GitBranch className="w-3 h-3" />
                {currentBranch} → {baseBranch}
              </span>
            )}
          </div>
        </div>
        <button
          onClick={() => onOpenChange(false)}
          className="p-1 rounded hover:bg-muted/30 transition-colors flex-shrink-0"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-1 space-y-3">
        {/* On base branch warning */}
        {currentBranch === baseBranch && (
          <div className="flex items-start gap-2 p-3 border border-dashed border-yellow-500/40 bg-yellow-500/5">
            <GitBranch className="w-4 h-4 text-yellow-500 shrink-0 mt-0.5" />
            <div>
              <p className="text-xs font-medium text-yellow-500 font-mono">[INFO] Base Branch</p>
              <p className="text-xs text-muted-foreground mt-0.5 font-mono">
                You're on {baseBranch}. Switch to a feature branch to see tasks.
              </p>
            </div>
          </div>
        )}

        {/* Loading States */}
        {!baseBranch && (
          <div className="flex items-center gap-2 py-4 justify-center">
            <RetroSpinner size={13} />
            <span className="text-xs text-muted-foreground font-mono">Detecting base branch...</span>
          </div>
        )}
        
        {(stage === 'loading' || stage === 'generating') && (
          <div className="flex items-center gap-2 py-4 justify-center">
            <RetroSpinner size={13} />
            <span className="text-xs text-muted-foreground font-mono">
              {stage === 'generating' ? '' : 'Loading...'}
            </span>
          </div>
        )}
        
        {/* Error State */}
        {error && (
          <div className="flex items-start gap-2 p-3 border border-dashed border-red-500/40 bg-red-500/5">
            <svg className="w-4 h-4 text-red-500 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
            <div>
              <p className="text-xs font-medium text-red-500 font-mono">[ERROR] Failed to generate tasks</p>
              <p className="text-xs text-red-400/80 mt-0.5 break-words font-mono">{error}</p>
            </div>
          </div>
        )}
        
        {/* No tasks */}
        {stage === 'done' && tasks.length === 0 && (
          <div className="p-3 text-center border border-dashed border-border">
            <p className="text-xs text-muted-foreground font-mono">No tasks generated</p>
            <p className="text-xs text-muted-foreground mt-0.5 font-mono">
              The LLM couldn't identify specific tasks from the changes
            </p>
          </div>
        )}
        
        {/* Tasks List */}
        {stage === 'done' && tasks.length > 0 && (
          <div className="space-y-2">
            {tasks.map((task, index) => {
              const isExpanded = expandedTasks.has(index);
              const hasFiles = task.files && task.files.length > 0;
              
              return (
                <div 
                  key={index}
                  className="border-b border-dashed border-border overflow-hidden"
                >
                  {/* Task Header */}
                  <button
                    onClick={() => hasFiles && toggleTaskExpansion(index)}
                    className={cn(
                      "w-full flex items-start gap-2 p-1 text-left hover:bg-muted/30 transition-colors",
                      hasFiles && "cursor-pointer"
                    )}
                  >
                 
                    <div className="flex-1 min-w-0">
                      <p className="font-mono text-xs leading-relaxed">
                        {task.title}
                      </p>

                      {hasFiles && (
                        <div className="flex items-center gap-1 mt-1">
                          <FileText className="w-3 h-3 text-muted-foreground" />
                          <span className="text-xs text-muted-foreground">
                            {task.files.length} file{task.files.length !== 1 ? 's' : ''}
                          </span>
                        </div>
                      )}
                    </div>
                    {hasFiles && (
                      <span className="flex-shrink-0 mt-0.5">
                        {isExpanded ? (
                          <ChevronDown className="w-4 h-4 text-muted-foreground" />
                        ) : (
                          <ChevronRight className="w-4 h-4 text-muted-foreground" />
                        )}
                      </span>
                    )}
                  </button>

                  {/* Expanded Details */}
                  {isExpanded && hasFiles && (
                    <div className="border-t border-dashed border-border bg-muted/20 px-3 py-2">
                      <p className="text-[10px] text-muted-foreground mb-1.5 font-mono uppercase tracking-wider">
                        Changed files
                      </p>
                      <div className="space-y-0.5">
                        {task.files.map((file, fileIndex) => (
                          <div 
                            key={fileIndex}
                            className="font-mono text-xs text-muted-foreground truncate pl-2"
                            title={file}
                          >
                            • {file}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>

      
    </div>
  );
}
